# Generated by Django 3.2.7 on 2021-09-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyCNPJ', models.CharField(max_length=20)),
                ('CompanyAdress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductQnt', models.IntegerField()),
                ('Category_CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.category')),
                ('Company_CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.companies')),
            ],
        ),
    ]
