# Generated by Django 3.2.7 on 2021-09-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryID',
            new_name='CategoryId',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyID',
            new_name='CompanyId',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category_CategoryID',
            new_name='Category_CategoryId',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Company_CompanyID',
            new_name='Company_CompanyId',
        ),
    ]
